version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend_container
    restart: always
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: frontend_container
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
